### PR TITLE
fix: add missing 'n' in PackageJson.depe(n)dencies

### PR DESCRIPTION
**Pull request by forivall**

### CODE REVIEW

**Comment by soldair** [comment]
This looks great! ping @chrisdickinson

**Comment by soldair** [comment]
@ahmadnassri give us a merge and release please?

**Comment by fraxken** [comment]
@darcyclarke 👋 If you have time to merge and release a patch 🙇.

**Review by EscapeB — APPROVED** [review]

**Comment by EscapeB** [comment]
@chrisdickinson Could you please help to merge this PR and release a patch? It has been 4 years...

**Review by darcyclarke — APPROVED** [review]

**Pull request merged**
