### PR TITLE
feat: all the things! 

### PR DESCRIPTION
**Pull request by soldair**
types for npm related objects!

### CODE REVIEW

**Comment by soldair** [comment]
ping @chrisdickinson 
i think this is ready to merge/review =)

/cc @ofrobots

**Comment by soldair** [comment]
i will fix this. perfect suggestion.

I was also wondering i think there is a third type of document? pacote has a method called "manifest" i wanted to make sure that AbbreviatedDocument (corgi) is not also the manifest cached by pacote

**Comment by zkat** [comment]
@soldair `pacote.manifest()` returns corgis by default, and the full manifest if you do `opts = { fullMetadata: true }`

**Comment by soldair** [comment]
oh thanks @zkat 
in that case i would like to rename AbbreviatedPackument to Manifest its an extremely better name 

whatcha think?

**Comment by soldair** [comment]
ok i intend to change AbbreviatedPackument to Manifest

**Comment by chrisdickinson** [comment]
Thank you so much for this! Publishing as `@npm/types @ 1.0.0`.

**Comment by soldair** [comment]
```
curl https://registry.npmjs.org/@npm%2ftypes
{"error":"Not found"}
```
maybe went private?

**Comment by chrisdickinson** [comment]
Ack! Good catch. I have made the package public (at 1.0.1 because _reasons_ :sparkles:)

**Comment by styfle** [comment]
Any reason why these types are not shipped with `pacote` or `npm`?

**Comment by zkat** [comment]
Because we don't do typescript ourselves and I wasn't about to go through the trouble? I'll take a PR, though :)

**Comment by soldair** [comment]
I hope we can import these into the d.ts files of other projects to reduce
duplicated effort. This is just one step.

**Comment by zkat** [comment]
@styfle it is non zero amounts of work for me in a storm of priorities. It doesn't matter if it's easy. If it's easy, all the more reason to get a PR from someone

**Pull request merged**
